name: cgpa_calculator
description: "A new Flutter project for CGPA calculation."

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Icons for iOS-style widgets
  cupertino_icons: ^1.0.8

  # Google Fonts package to use Noto fonts or any other easily
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

